### PR TITLE
TRITON-2479 sdcnode version 18 needs newer madvise patch for older platforms

### PR DESCRIPTION
**Pull request by teutat3s**
sdcnode version 18.20.6 build on minimal-64-lts 24.4.1 currently fails with 

```
../deps/v8/src/base/platform/platform-posix.cc: In static member function 'static bool v8::base::OS::DiscardSystemPages(void*, std::size_t)':
../deps/v8/src/base/platform/platform-posix.cc:517:13: error: 'madvise' was not declared in this scope
517 |   int ret = madvise(reinterpret_cast<caddr_t>(address), size, MADV_FREE);
    |             ^~~~~~~
make[2]: *** [tools/v8_gypfiles/v8_libbase.target.mk:175: 
/root/data/jenkins/workspace/TritonDataCenter_sdcnode_master/build/nodes/v18.20.6/
src/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-posix.o] Error 1
```

### CODE REVIEW

**Review by nshalman — DISMISSED** [review]
Looks good to me.

**Review by danmcd — DISMISSED** [review]
Approved with the caveats of:

- Needs at least one more reviewer.
- Full test notes in ticket.
- I asked Node if my madvise (under review, hope to land it in node's `main`) could be backported to *supported* node versions (20, 22, 24).  IF They do it, this patch will already be in the source.  Something to be aware of.

**Review by cneira — DISMISSED** [review]
Patch looks good to me.

**Comment by teutat3s** [comment]
Thank you for the reviews, I added another commit for `build_tags`. This commit could also move into a separate PR if preferred.

**Comment by danmcd** [comment]
Including build_tags here is okay as long as it passes the same tests as WITHOUT this change AND/OR unlocks new working cases.

You can also rename the bug summary to cover all of the relevant change here.

**Comment by danmcd** [comment]
TO BE CLEAR: build tags should be their own commit or at LEAST their own TRITON issue.

**Comment by teutat3s** [comment]
I created #16 to address Dan's comment.

**Review by danmcd — APPROVED** [review]
Do not push until @cneira has re-reviewed as well, please.

**Review by cneira — APPROVED** [review]
The changes look good to me. In the past, I sometimes found myself converting the old Joyent URLs to our new Triton DataCenter ones whenever I needed to read some documentation, but I’d forget to point out the issue. Thanks for making this change!
